version: '2.1'

services:

  # The Cookie on Demand service, a J2E system
  tcf_system:
    image: docker-j2e
    container_name: tcf_j2e
    environment:
      - bank_host=tcf_dotnet
      - bank_port=9090
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - external_partners

  # The external partners, implemented as .Net services
  external_partners:
    image: docker-dotnet
    container_name: tcf_dotnet
    expose:
        - "9090"
    ports:
      - "9090:9090"

  # A simple java CLI
  client:
    image: docker-client
    container_name: tcf_client
    command: "tcf_system 8080"
    volumes:
      - .:/host
    depends_on:
      tcf_system:
        condition: service_healthy
    stdin_open: true
    tty: true
